name:                wheatley
version:             0.1.0.0
github:              "isovector/wheatley"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2020 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/wheatley#readme>

default-extensions:
  - OverloadedStrings
  - GADTs
  - TypeFamilies
  - TypeOperators
  - DataKinds
  - ScopedTypeVariables
  - LambdaCase
  - ViewPatterns
  - FlexibleInstances
  - FlexibleContexts
  - UndecidableInstances
  - KindSignatures
  - DeriveFunctor
  - DeriveGeneric
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - GeneralizedNewtypeDeriving
  - DeriveAnyClass
  - StandaloneDeriving

dependencies:
- base-noprelude >= 4.7 && < 5
- base-prelude
- megaparsec
- text

library:
  source-dirs: src

